version: '3'
services:

  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db_template

  sqs:
    image: s12v/elasticmq
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq.conf:/etc/elasticmq/elasticmq.conf

  mock:
    image: rodolpheche/wiremock:2.26.3-alpine
    ports:
    - "5000:8080"
    - "8443:8443"
    volumes:
    - ${PWD}/mock:/home/wiremock

